export const APP = {
    VERSION: "VERSION"
  };
  export const USER = {
    REGISTER: "REGISTER",
    REGISTER_ACCESS:"REGISTER_ACCESS",
    REGISTER_FAILED:"REGISTER_FAILED",
    LOGIN: "LOGIN",
    LOGIN_ACCESS:"LOGIN_ACCESS",
    LOGIN_FAILED:"LOGIN_FAILED",
    LOGOUT: "LOGOUT",
    FORGETPASSWORD: "FORGETPASSWORD",
    MODIFYUSERINFO: "MODIFYUSERINFO",
    CHANGEPASSWORD: "CHANGEPASSWORD",
    UPLOADPICTURE: "UPLOADPICTURE",
    GETINFO: "GETUSERINFO",
    GETTOKEN: "GETUSERTOKEN"
  };
  export const FAVORITE = {
    APPEND: "APPENDINTOFAVORITE",
    DELETE: "DELETEITEMFROMFAVORITE",
    GET: "GETFAVORITE"
  };
  export const SEARCH = {
    ETFSYMBOL: "ETFSYMBOL",
    STOCKPRICE: "STOCKPRICE"
  };
  